/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BD.Conexion;
import Clases.Categoria;
import Clases.Pregunta;
import Clases.Respuesta;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author joaco
 */
public class nuevaPregunta extends javax.swing.JFrame {

    /**
     * Creates new form nuevaPregunta
     */
    public nuevaPregunta() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        
        List<Categoria> categorias = Conexion.getInstance().listadoCategorias();

        categorias.forEach((c) -> {
            this.cboCategoria.addItem(c);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRespuestaCorrecta = new javax.swing.JTextField();
        txtRespuestaIncorrecta1 = new javax.swing.JTextField();
        txtRespuestaIncorrecta2 = new javax.swing.JTextField();
        txtRespuestaIncorrecta3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPregunta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxNivelCategoria = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtPuntosCategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Pregunta");

        jButton1.setText("Crear Pregunta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Respuesta correcta: ");

        jLabel2.setText("Respuesta 2: ");

        jLabel3.setText("Respuesta 3: ");

        jLabel4.setText("Respuesta 4: ");

        jLabel5.setText("Pregunta: ");

        txtPregunta.setColumns(20);
        txtPregunta.setRows(5);
        jScrollPane1.setViewportView(txtPregunta);

        jLabel6.setText("Categoría: ");

        jLabel7.setText("Nivel: ");

        cbxNivelCategoria.setMaximumRowCount(5);
        cbxNivelCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        cbxNivelCategoria.setToolTipText("");

        jLabel8.setText("Puntos: ");

        txtPuntosCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntosCategoriaActionPerformed(evt);
            }
        });
        txtPuntosCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuntosCategoriaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(5, 5, 5))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(62, 62, 62)
                            .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRespuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel8))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRespuestaIncorrecta1)
                                .addComponent(txtRespuestaIncorrecta2)
                                .addComponent(txtRespuestaIncorrecta3)
                                .addComponent(cbxNivelCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPuntosCategoria)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRespuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRespuestaIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRespuestaIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRespuestaIncorrecta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxNivelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPuntosCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pregunta = txtPregunta.getText();
        String respuestaCorrecta = txtRespuestaCorrecta.getText();
        String respuestaIncorrecta1 = txtRespuestaIncorrecta1.getText();
        String respuestaIncorrecta2 = txtRespuestaIncorrecta2.getText();
        String respuestaIncorrecta3 = txtRespuestaIncorrecta3.getText();
            
        
        
        //Chequeo valores vacíos.
        if(pregunta.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la pregunta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else if(respuestaCorrecta.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la respuesta correcta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else if(respuestaIncorrecta1.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la respuesta incorrecta 1", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else if(respuestaIncorrecta2.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la respuesta incorrecta 2", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else if(respuestaIncorrecta3.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la respuesta incorrecta 3", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else if(this.txtPuntosCategoria.getText().isEmpty()){
            
        }else{
            int puntosCategoria = Integer.valueOf(this.txtPuntosCategoria.getText());
            int nivelCategoria = Integer.valueOf(this.cbxNivelCategoria.getSelectedItem().toString());
            
            //Creo la pregunta
            Pregunta p = new Pregunta();
            p.setDescripcion(pregunta);
            p.setNivel(nivelCategoria);
            p.setPuntos(puntosCategoria);
            p.setCategoria((Categoria) cboCategoria.getSelectedItem());
            
            //Creo las respuestas
            Respuesta r1 = new Respuesta();
            Respuesta r2 = new Respuesta();
            Respuesta r3 = new Respuesta();
            Respuesta r4 = new Respuesta();

            r1.setDescripcion(respuestaCorrecta);
            r1.setIsCorrecta(true);

            r2.setDescripcion(respuestaIncorrecta1);
            r2.setIsCorrecta(false);

            r3.setDescripcion(respuestaIncorrecta2);
            r3.setIsCorrecta(false);

            r4.setDescripcion(respuestaIncorrecta3);
            r4.setIsCorrecta(false);

            List<Respuesta> respuestas = new ArrayList<>(); 
            respuestas.add(r1);
            respuestas.add(r2);
            respuestas.add(r3);
            respuestas.add(r4);                 
            p.setRespuestas(respuestas);
            
            boolean exito = Conexion.getInstance().persist(p);
            if(exito){           
                //Muestro alerta y limpio los campos...
                javax.swing.JOptionPane.showMessageDialog(this, "Se ha creado la pregunta correctamente.");
                this.txtPregunta.setText("");
                this.txtRespuestaCorrecta.setText("");
                this.txtRespuestaIncorrecta1.setText("");
                this.txtRespuestaIncorrecta2.setText("");
                this.txtRespuestaIncorrecta3.setText("");
                this.txtPuntosCategoria.setText("");    
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPuntosCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntosCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntosCategoriaActionPerformed

    private void txtPuntosCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntosCategoriaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();  // if it's not a number, ignore the event
        }
    }//GEN-LAST:event_txtPuntosCategoriaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevaPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevaPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevaPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevaPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevaPregunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Categoria> cboCategoria;
    private javax.swing.JComboBox cbxNivelCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPregunta;
    private javax.swing.JTextField txtPuntosCategoria;
    private javax.swing.JTextField txtRespuestaCorrecta;
    private javax.swing.JTextField txtRespuestaIncorrecta1;
    private javax.swing.JTextField txtRespuestaIncorrecta2;
    private javax.swing.JTextField txtRespuestaIncorrecta3;
    // End of variables declaration//GEN-END:variables
}
